name: '0000'
channels:
  - conda-forge
dependencies:
  - python=3
  - jupyterlab
  - notebook
  - ipython
  - jupyter
  - dask
  - openpyxl
  - scipy
  - vaex
  - pandas
  - pyreadstat
  - numpy
  - polars
  - pyarrow
  - jupysql
  - python-duckdb
  - duckdb-engine
  - plotly
  - matplotlib
  - seaborn
  - lime
  - eli5
  - shap
  - scikit-learn
  - statsmodels
  - pymc3
  - pytorch
  - tensorflow
  - pytorch_geometric
  - keras
